version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8070:8070"
    environment:
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=student123
    networks:
      - app-network

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: student123
      MYSQL_DATABASE: your_database_name
    volumes:
      - data_db:/var/lib/mysql
    networks:
      - app-network

volumes:
  data_db:

networks:
  app-network: